version: '3.8'

services:
  cups:
    build: ./cupsserver
    ports:
      - 8080:631
    volumes:
      - ./cupsserver:/home/print
      - /var/run/dbus:/var/run/dbus
    command: /usr/sbin/cupsd -f
  web:
    depends_on:
      - cups
    build: ./webserver
    volumes:
      - ./webserver:/server
    ports:
      - "8000:8000"
    command: flask run --host=0.0.0.0 --port=8000
