version: '3.8'

services:
  cups:
    build: ./cupsserver
    ports:
      - 631
    volumes:
      - ./cupsserver:/home/print
      - /var/run/dbus:/var/run/dbus
    command: bash -c "/usr/sbin/cupsd && /home/print/addprinter.sh && tail -F YOU_CAN_IGNORE_THIS_ERROR"
  web:
    depends_on:
      - cups
    build: ./webserver
    volumes:
      - ./webserver:/server
    ports:
      - 8007:8000
    command: flask run --host=0.0.0.0 --port=8000
