version: '3.9'
services:
  cups:
    image: cups:latest
    build:
      context: ./build/cups
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./print:/print
      - /var/run/dbus:/var/run/dbus
    ports:
      - "631:631"
    restart: always

  web:
    image: pdfprinter:latest
    build:
      context: ./
      dockerfile: build/web/Dockerfile
    env_file: .env
    depends_on:
      - cups
    volumes:
      - ./print:/print
    ports:
      - "8007:8000"
    restart: always
